name: Deploy to GitHub Pages

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  test-deploy:
    if: github.event_name != 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Test build website
        run: npm run build
  deploy:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - name: Deploy to GitHub Pages
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "gh-actions"

          npm ci
          npm run build

          mkdir /tmp/docusaurusbuild
          mv build /tmp/docusaurusbuild

          git checkout gh-pages
          rm -r *
          mv /tmp/docusaurusbuild/build/* .
          git add -A
          git commit -m "Automated Build From Github Actions"
          git push